config/routes.rb
CatchUpWithRor4::Application.routes.draw do
  
  root "test#index"

  resources :stream, only: [:index] #/stream
  get "stream/index"
  resources :categories do 
    resources :comments
  end
  
  resources :products do 
    resources :comments
  end

  get "test/index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :commentable, polymorphic: true, touch: true
  # touch: true for update relation in object
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # new feature in rails 4 
  add_flash_types :warning 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, product_ids: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable

  def index
    # refactored to before_action
    # @commentable = Product.find(params[:product_id])
    
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_to [@commentable, :comments], notice: "Comment created."
      
      # to for example /photo/2 (to corrent object)
      # redirect_to @commentable, notice: "Comment created."
    else
      render :new
    end
  end

private

  # with standart URL format
  def load_commentable
    resource, id = request.path.split('/')[1,2] # split by slash and grab 1st and 2nd element in array
    # products/1
    @commentable = resource.singularize.classify.constantize.find(id)
    # converted to Product.find(1)
  end

  # more specific technique
  # def load_commentable
  #   klass = [Product, Category].detect { |c| params["#{c.name.underscore}_id"]}
  #   @commentable = klass.find(params["#{klass.name.underscore}_id"])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content)
  end
 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_filter # were in Rails 3
  
  def index
    @products = Product.all
  end

  def show
    @commentable = @product
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    # Rails 3 way
    # if true
    #   flash[:warning] = "my message"
    # end

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, warning: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :body, :category_id)
    end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController
  include ActionController::Live
 
  def index
    begin
      response.headers["Content-Type"] = "text/event-stream"
      # response.stream.write "hello world\n\n"
      # response.stream.close    
      10.times { |i|
        response.stream.write "data: #{i}\n\n"
        sleep 2
      }
    rescue IOError
      # ... 
    ensure
      response.stream.close
    end 
  end

end

app/controllers/test_controller.rb
class TestController < ActionController::Base
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<!-- <%= render 'form' %> -->
<%= form_for @category do |f| %>
  <%= f.text_field :name %>

  <%= f.collection_check_boxes :product_ids, Product.all, :id, :title do |b| %>
    <br />
    <%= b.label(:"data-value" => b.value) { b.check_box + ' ' + b.text } %>
  <% end %>
 
   <br />
   <%= f.submit %>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back to list of categories', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comments.html.erb
<div id="comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <%= simple_format comment.content %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= render "comments" %>

<p><%= link_to "New comment", [:new, @commentable, :comment] %> </p>

app/views/comments/new.html.erb
<h1>New Comments</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catch Up With RoR 4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= content_tag :div, flash[:warning] if flash[:warning] %>
  <div class="container" class="row">
    <%= yield %>  
  </div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <!-- <%= f.collection_select :category_id, Category.all, :id, :name %> -->
    <!-- <%= f.collection_radio_buttons :category_id, Category.all, :id, :name %> -->
    <%= f.collection_radio_buttons :category_id, Category.all, :id, :name  do |b| %>    
      <%= b.label(:"data-value" => b.value) { b.radio_button + ' ' + b.text} %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.body %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% cache @product do %>
<% #cache ['v3', @product] do # this not needed with gem 'cache_digests'%>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @product.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @product.body %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @product.category.name %>
  </p>

  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>

  <h2>Comments</h2>

  <%= render "comments/comments" %>
  <%= render "comments/form" %>

<% end %>

app/views/stream/index.html.erb
<h1>Stream#index</h1>
<p>Find me in app/views/stream/index.html.erb</p>